import {
  Ruler,
  Thermometer,
  Coins,
  Weight,
  Calculator,
  Landmark,
  TrendingUp,
  Tag,
  ShieldCheck,
  Code,
  QrCode,
  Search,
  Activity,
  Droplets,
  Timer,
  ListTodo,
} from "lucide-react-native";

export const TOOL_SECTIONS = [
  {
    id: "converters",
    title: "CONVERSION TOOLS",
    tools: [
      {
        id: "length",
        icon: Ruler,
        title: "Length",
        description: "CM, Inches, Feet, Kilometers",
        color: "#6366F1",
        type: "converter",
      },
      {
        id: "temperature",
        icon: Thermometer,
        title: "Temperature",
        description: "Celsius, Fahrenheit, Kelvin",
        color: "#EF4444",
        type: "converter",
      },
      {
        id: "currency",
        icon: Coins,
        title: "Currency",
        description: "Live exchange rates (USD, EUR, GBP)",
        color: "#10B981",
        type: "converter",
      },
      {
        id: "weight",
        icon: Weight,
        title: "Weight",
        description: "KG, Pounds, Ounces, Grams",
        color: "#8B5CF6",
        type: "converter",
      },
    ],
  },
  {
    id: "finance",
    title: "FINANCE & MATH",
    tools: [
      {
        id: "tip",
        icon: Calculator,
        title: "Tip Calculator",
        description: "Smart splitting and percentage",
        color: "#10B981",
        route: "/tools/tip-calculator",
      },
      {
        id: "loan",
        icon: Landmark,
        title: "Loan Calc",
        description: "Mortgage and loan payments",
        color: "#F59E0B",
        route: "/tools/loan-calculator",
      },
      {
        id: "investment",
        icon: TrendingUp,
        title: "Investment",
        description: "Compound interest & ROI",
        color: "#8B5CF6",
        route: "/tools/investment-calculator",
      },
      {
        id: "discount",
        icon: Tag,
        title: "Discount",
        description: "Sale price and tax calculator",
        color: "#10B981",
        route: "/tools/discount-calculator",
      },
    ],
  },
  {
    id: "security",
    title: "SECURITY & DATA",
    tools: [
      {
        id: "pwd-gen",
        icon: ShieldCheck,
        title: "Password Gen",
        description: "Secure locally generated keys",
        color: "#3B82F6",
        route: "/tools/password-generator",
      },
      {
        id: "base64",
        icon: Code,
        title: "Base64 Tool",
        description: "Encode and decode text data",
        color: "#6366F1",
        route: "/tools/base64-tool",
      },
      {
        id: "qr-gen",
        icon: QrCode,
        title: "QR Generator",
        description: "Create custom QR codes",
        color: "#F59E0B",
        route: "/tools/qr-generator",
      },
      {
        id: "qr-scan",
        icon: Search,
        title: "QR Scanner",
        description: "Scan codes via camera",
        color: "#00D4FF",
        route: "/tools/qr-scanner",
      },
    ],
  },
  {
    id: "health",
    title: "HEALTH & TIME",
    tools: [
      {
        id: "bmi",
        icon: Activity,
        title: "BMI Calculator",
        description: "Health index based on body stats",
        color: "#EF4444",
        route: "/tools/bmi-calculator",
      },
      {
        id: "water",
        icon: Droplets,
        title: "Water Tracker",
        description: "Daily hydration monitoring",
        color: "#00D4FF",
        route: "/tools/water-tracker",
      },
      {
        id: "timer",
        icon: Timer,
        title: "Stopwatch",
        description: "High-precision time tracking",
        color: "#8B5CF6",
        route: "/tools/timer-tool",
      },
    ],
  },
  {
    id: "productivity",
    title: "PRODUCTIVITY",
    tools: [
      {
        id: "tasks",
        icon: ListTodo,
        title: "Task List",
        description: "Create & manage your to-dos",
        color: "#6366F1",
        route: "/tools/task-manager",
      },
    ],
  },
];
